# RDM/case 配置：供 FlinkMain 入口使用（args[0] 指向本文件路径）
# 指定实际加载的 application 配置文件名（不要前缀 / 和 .properties，代码会拼成 /application-dev.properties）
properties_file=application-dev.properties
start_timestamp=0
fail_on_cp_errors=false
kafka_producer_retries=0
kafka_producer_ack=-1
framework.streaming.appName=FlinkApp
